name: master Build Matrix

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_ubuntu_20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: jurplel/install-qt-action@v2
        with:
          version: "5.12.8"

      - name: make
        run: make

  build_ubuntu_18:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: jurplel/install-qt-action@v2
        with:
          version: "5.9.5"

      - name: make
        run: make

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies via brew
        run: brew install qt@5 openssl

      - uses: jurplel/install-qt-action@v2
        with:
          version: "5.12.8"

      - name: make
        run: make build/kristall

      - name: Prepare deployment
        working-directory: build
        run: macdeployqt kristall.app -dmg

      - name: display
        run: |
          uname -a
          file build/kristall.app 
          ls build

      - uses: actions/upload-artifact@v2
        with:
          name: Kristall.app
          path: build/kristall.dmg

      - name: Deploy with SCP
        uses: noobly314/deploy-with-scp@v1
        with:
          src: build/kristall.dmg
          dest: kristall/Kristall-nightly-macos-x86_64.dmg
          username: generic-ci
          server-ip: random-projects.net
          ssh-key: ${{ secrets.PRIVATE_KEY }} #

      # - name: Deploy via SCP
      #   uses: horochx/deploy-via-scp@master
      #   with:
      #     local: build/kristall.app
      #     remote: kristall/Kristall-nightly-macos-x86_64.app
      #     host: random-projects.net
      #     port: 22
      #     user: generic-ci
      #     key: ${{ secrets.PRIVATE_KEY }} #
      #
      # - name: Deploy via SCP
      #   uses: garygrossgarten/github-action-scp@release
      #   with:
      #     host: random-projects.net
      #     username: generic-ci
      #     privateKey: ${{ secrets.PRIVATE_KEY }}
      #     local: "build/kristall.app"
      #     remote: "kristall/Kristall-nightly-macos-x86_64.app"
#

# Disabled until both aqinstall and install-qt-action support the fixes…
#  build_windows:
#    runs-on: windows-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: MasterQ32/install-qt-action@master
#      with:
#        version: '5.15.0'
#        host: 'windows'
#        target: 'desktop'
#        arch: 'win64_mingw81'
#        install-deps: 'true'
#        tools: 'tools_openssl_x64 qt.tools.openssl.win_x64;tools_openssl_src qt.tools.openssl'
#    - name: build and deploy
#      run: ./build-and-deploy.bat
#      working-directory: ./ci/
